import type { ReceiptResponse } from "@fiber-merchantops/shared";

const RECEIPT_ROWS: ReadonlyArray<
  [label: string, key: keyof ReceiptResponse]
> = [
  ["Receipt ID", "receipt_id"],
  ["Merchant ID", "merchant_id"],
  ["Order ID", "order_id"],
  ["Payment Intent ID", "payment_intent_id"],
  ["Asset", "asset"],
  ["Amount", "amount"],
  ["Payment Hash", "payment_hash"],
  ["Paid At", "paid_at"],
  ["Status", "status"],
];

export function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

/** Renders the self-contained HTML receipt served at /v1/receipts/:id.html. */
export function renderReceiptHtml(receipt: ReceiptResponse): string {
  const rows = RECEIPT_ROWS.map(([label, key]) => {
    const value = receipt[key];
    const display = value === null ? "n/a" : escapeHtml(String(value));
    return `      <tr><th>${label}</th><td>${display}</td></tr>`;
  }).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Receipt ${escapeHtml(receipt.receipt_id)}</title>
    <style>
      body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 40rem; color: #1a1a1a; }
      h1 { font-size: 1.25rem; border-bottom: 2px solid #1a1a1a; padding-bottom: 0.5rem; }
      table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
      th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #ddd; vertical-align: top; }
      th { width: 12rem; color: #555; font-weight: 600; white-space: nowrap; }
      td { word-break: break-all; }
      footer { margin-top: 1.5rem; font-size: 0.8rem; color: #777; }
    </style>
  </head>
  <body>
    <h1>Payment Receipt</h1>
    <table>
${rows}
    </table>
    <footer>Generated by Fiber MerchantOps Core</footer>
  </body>
</html>
`;
}
